# Generated by Django 3.2.5 on 2021-07-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_siteuser_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HABModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_submission', models.DateTimeField(auto_now_add=True)),
                ('roll_number', models.IntegerField(verbose_name='Roll No.')),
                ('hostel', models.CharField(choices=[('Lohit', 'Lohit'), ('Brahmaputra', 'Brahmaputra')], max_length=256, verbose_name='Hostel')),
                ('date_of_arrival', models.DateField(verbose_name='Date of Arrival')),
                ('fee_paid', models.IntegerField(verbose_name='Fee Paid')),
                ('fee_receipt', models.FileField(upload_to='', verbose_name='Fee Receipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.siteuser')),
            ],
        ),
    ]
