# Generated by Django 3.2.5 on 2021-09-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='registered_for_academic_semester',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=True, verbose_name='Registered for Academic Semester'),
        ),
    ]
