# Generated by Django 3.2.5 on 2021-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0002_alter_habmodel_registered_for_academic_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='registered_for_academic_semester',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Registered for Academic Semester'),
        ),
    ]
