# Generated by Django 3.2.5 on 2021-07-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0002_habmodel_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='fee_receipt',
            field=models.FileField(blank=True, upload_to='', verbose_name='Fee Receipt'),
        ),
    ]
