# Generated by Django 3.2rc1 on 2021-07-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0003_auto_20210723_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habmodel',
            options={'ordering': ['-date_of_arrival']},
        ),
    ]
