# Generated by Django 3.2.5 on 2021-07-24 05:16

from django.db import migrations, models
import hab_portal.models
import hab_portal.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0003_auto_20210723_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='fee_receipt',
            field=models.FileField(help_text='Upload a .PDF file not greater than 10 MB in size.', storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.upload_file_name, validators=[hab_portal.models.validate_file_size, hab_portal.models.validate_file_extension], verbose_name='Fee Receipt'),
        ),
    ]
