# Generated by Django 3.2.5 on 2021-09-07 14:12

import datetime
from django.db import migrations, models
import hab_portal.models
import hab_portal.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0003_alter_habmodel_registered_for_academic_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='check_in_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Check-in Date'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='date_of_arrival',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date of Arrival'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='date_of_payment',
            field=models.DateField(null=True, verbose_name='Date of Payment'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='date_of_testing',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Date of Test'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='fee_receipt',
            field=models.FileField(help_text='Upload a .PDF file not greater than 10 MB in size.', null=True, storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.fee_upload_file_name, validators=[hab_portal.models.validate_file_size, hab_portal.models.validate_file_extension], verbose_name='Fee Receipt'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='flight_train_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Flight / Train No.'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='hostel',
            field=models.CharField(choices=[('lohit', 'Lohit'), ('brahmaputra', 'Brahmaputra'), ('siang', 'Siang'), ('manas', 'Manas'), ('disang', 'Disang'), ('kameng', 'Kameng'), ('umiam', 'Umiam'), ('barak', 'Barak'), ('kapili', 'Kapili'), ('dihing', 'Dihing'), ('subansiri', 'Subansiri'), ('dhansiri', 'Dhansiri'), ('msh', 'Married Scholar Hostel')], max_length=256, null=True, verbose_name='Hostel'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='mode_of_travel',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Mode of Travel'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='nature_of_test',
            field=models.CharField(choices=[('RT-PCR', 'RT-PCR'), ('TrueNat', 'TrueNat')], max_length=256, null=True, verbose_name='Nature of Test'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='returning_from_state',
            field=models.CharField(max_length=256, null=True, verbose_name='Returning from (state)'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='room_no',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='rtpcr_report',
            field=models.FileField(help_text='Upload a .PDF file not greater than 10 MB in size.', null=True, storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.rtpcr_upload_file_name, validators=[hab_portal.models.validate_file_size, hab_portal.models.validate_file_extension], verbose_name='RTPCR Report'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='travel_ticket',
            field=models.FileField(help_text='Upload a .PDF file not greater than 10 MB in size.', null=True, storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.travel_upload_file_name, validators=[hab_portal.models.validate_file_size, hab_portal.models.validate_file_extension], verbose_name='Travel Ticket'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='vaccination_cert',
            field=models.FileField(help_text='Upload a .PDF file not greater than 10 MB in size.', null=True, storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.vacc_upload_file_name, validators=[hab_portal.models.validate_file_size, hab_portal.models.validate_file_extension], verbose_name='Vaccination Certificate'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='vaccination_status',
            field=models.CharField(choices=[('Double Dose', 'Double Dose')], max_length=256, null=True, verbose_name='Vaccination Status'),
        ),
    ]
