# Generated by Django 3.2rc1 on 2021-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0004_alter_habmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Approved'), (1, 'Pending')], default=1),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='hostel',
            field=models.CharField(choices=[('Lohit', 'Lohit'), ('Brahmaputra', 'Brahmaputra'), ('Siang', 'Siang'), ('Manas', 'Manas'), ('Disang', 'Disang'), ('Kameng', 'Kameng'), ('Umiam', 'Umiam'), ('Barak', 'Barak'), ('Kapili', 'Kapili'), ('Dihing', 'Dihing'), ('Subansiri', 'Subansiri'), ('Dhansiri', 'Dhansiri'), ('Married Scholar Hostel', 'Married Scholar Hostel')], max_length=256, verbose_name='Hostel'),
        ),
    ]
