# Generated by Django 3.2.5 on 2021-09-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0004_auto_20210907_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='vaccination_status',
            field=models.CharField(choices=[('Single Dose', 'Single Dose'), ('Double Dose', 'Double Dose')], max_length=256, null=True, verbose_name='Vaccination Status'),
        ),
    ]
