# Generated by Django 3.2.5 on 2021-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0004_alter_habmodel_fee_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='date_of_payment',
            field=models.DateField(verbose_name='Date of Payment'),
        ),
        migrations.AddField(
            model_name='habmodel',
            name='department',
            field=models.CharField(default='enter department', max_length=256, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='habmodel',
            name='email',
            field=models.CharField(default='enter email id', max_length=500, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='habmodel',
            name='name',
            field=models.CharField(default='enter name', max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='hostel',
            field=models.CharField(choices=[('Lohit', 'Lohit'), ('Brahmaputra', 'Brahmaputra'), ('Umaim', 'Umaim'), ('Dihing', 'Dihing'), ('Disang', 'Disang'), ('Barak', 'Barak'), ('Kapili', 'Kapili'), ('Kameng', 'Kameng'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Dibang', 'Dibang'), ('Dhansiri', 'Dhansiri'), ('Subansiri', 'Subansiri')], max_length=256, verbose_name='Hostel'),
        ),
    ]
