# Generated by Django 3.2.5 on 2021-08-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0005_auto_20210806_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='roll_number',
            field=models.IntegerField(unique=True, verbose_name='Roll No.'),
        ),
    ]
