# Generated by Django 3.2.5 on 2021-09-07 15:48

from django.db import migrations, models
import hab_portal.models
import hab_portal.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0005_alter_habmodel_vaccination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='proof_of_invitation',
            field=models.FileField(help_text='Upload a .PDF file not greater than 10 MB in size.', null=True, storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.fee_upload_file_name, validators=[hab_portal.models.validate_file_size, hab_portal.models.validate_file_extension], verbose_name='Proof of Invitation'),
        ),
        migrations.AddField(
            model_name='habmodel',
            name='recieved_an_invite',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, null=True, verbose_name='Have you Recieved an Invite'),
        ),
    ]
