# Generated by Django 3.2.5 on 2021-07-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0006_alter_habmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
