# Generated by Django 3.2.5 on 2021-09-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0002_auto_20210907_1836'),
        ('hab_portal', '0006_auto_20210907_2118'),
    ]

    operations = [
    ]
