# Generated by Django 3.2.5 on 2021-08-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0006_alter_habmodel_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='date_of_payment',
            field=models.DateField(default='yyyy-mm-dd', verbose_name='Date of Payment'),
        ),
    ]
