# Generated by Django 3.2.5 on 2021-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0007_merge_0002_auto_20210907_1836_0006_auto_20210907_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=256, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='nature_of_test',
            field=models.CharField(choices=[('RT-PCR', 'RT-PCR'), ('TrueNat', 'TrueNat')], default='RT-PCR', max_length=256, null=True, verbose_name='Nature of Test'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='registered_for_academic_semester',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Registered for Academic Semester'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='vaccination_status',
            field=models.CharField(choices=[('Single Dose', 'Single Dose'), ('Double Dose', 'Double Dose')], default='Single Dose', max_length=256, null=True, verbose_name='Vaccination Status'),
        ),
    ]
