# Generated by Django 3.2.5 on 2021-07-26 10:44

from django.db import migrations, models
import hab_portal.models
import hab_portal.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0007_habmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habmodel',
            options={'ordering': ['status', 'date_of_arrival']},
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='fee_receipt',
            field=models.FileField(help_text='Upload a .PDF file not greater than 10 MB in size.', storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.upload_file_name, validators=[hab_portal.models.validate_file_size, hab_portal.models.validate_file_extension], verbose_name='Fee Receipt'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
