# Generated by Django 3.2.5 on 2021-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0008_alter_habmodel_date_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='fee_to_be_paid',
            field=models.IntegerField(default=-150, verbose_name='Fee to be Paid'),
        ),
    ]
