# Generated by Django 3.2.5 on 2021-09-08 05:35

from django.db import migrations, models
import hab_portal.models
import hab_portal.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0008_auto_20210908_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='final_pdf',
            field=models.FileField(null=True, storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.final_pdf_file_name, verbose_name='final pdf'),
        ),
    ]
