# Generated by Django 3.2.5 on 2021-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0008_auto_20210726_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habmodel',
            options={'ordering': ['status', '-date_of_arrival']},
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
