# Generated by Django 3.2.5 on 2021-08-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0009_habmodel_fee_to_be_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habmodel',
            name='fee_to_be_paid',
        ),
    ]
