# Generated by Django 3.2.5 on 2021-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0009_auto_20210726_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
