# Generated by Django 3.2.5 on 2021-09-09 11:09

from django.db import migrations, models
import hab_portal.models
import hab_portal.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0009_habmodel_final_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habmodel',
            name='registered_for_academic_semester',
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='hostel',
            field=models.CharField(choices=[('lohit', 'Lohit'), ('brahmaputra', 'Brahmaputra'), ('siang', 'Siang'), ('manas', 'Manas'), ('disang', '*Disang'), ('kameng', 'Kameng'), ('umiam', 'Umiam'), ('barak', 'Barak'), ('kapili', 'Kapili'), ('dihing', 'Dihing'), ('subansiri', 'Subansiri'), ('dhansiri', 'Dhansiri'), ('msh', 'Married Scholar Hostel'), ('not-alloted', 'Not Alloted')], max_length=256, null=True, verbose_name='Hostel'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='proof_of_invitation',
            field=models.FileField(blank=True, help_text='Upload screenshot of mail received from student affairs. Upload an image file of .jpg, .jpeg or .png extension.', null=True, storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.proof_of_invitation_file_name, validators=[hab_portal.models.validate_file_size, hab_portal.models.validate_file_extension_image], verbose_name='Proof of Invitation'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='recieved_an_invite',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=256, null=True, verbose_name='Have you Recieved an Invite'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='returning_from_state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry')], max_length=256, null=True, verbose_name='Returning from (state)'),
        ),
    ]
