# Generated by Django 3.2.5 on 2021-08-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0010_remove_habmodel_fee_to_be_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='fee_to_be_paid',
            field=models.IntegerField(default=17, verbose_name='Fee to be Paid'),
        ),
    ]
