# Generated by Django 3.2.5 on 2021-07-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0010_alter_habmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habmodel',
            name='slug',
        ),
    ]
