# Generated by Django 3.2.5 on 2021-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0011_auto_20210910_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Not Verified', 'Not Verified')], default='Not Verified', max_length=256, null=True),
        ),
    ]
