# Generated by Django 3.2.5 on 2021-07-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0011_remove_habmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
