# Generated by Django 3.2.5 on 2021-08-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0012_auto_20210807_0040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='date',
        ),
    ]
