# Generated by Django 3.2rc1 on 2021-07-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0013_auto_20210727_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habmodel',
            options={'ordering': ['hostel', '-status', 'date_of_arrival'], 'permissions': (('can_view_lohit_hostel_data', 'can view hostel data'),)},
        ),
    ]
