# Generated by Django 3.2.5 on 2021-09-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0013_auto_20210911_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='hostel',
            field=models.CharField(choices=[('lohit', 'Lohit'), ('brahmaputra', 'Brahmaputra'), ('siang', 'Siang'), ('manas', 'Manas'), ('dibang', 'Dibang'), ('disang', '*Disang'), ('kameng', 'Kameng'), ('umiam', 'Umiam'), ('barak', 'Barak'), ('kapili', 'Kapili'), ('dihing', 'Dihing'), ('subansiri', 'Subansiri'), ('dhansiri', 'Dhansiri'), ('dibang', 'Dibang'), ('msh', 'Married Scholar Hostel'), ('not-alloted', 'Not Alloted')], max_length=256, null=True, verbose_name='Hostel'),
        ),
    ]
