# Generated by Django 3.2.5 on 2021-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0013_delete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_arrival', models.DateField(verbose_name='Date of Arrival')),
            ],
        ),
    ]
