# Generated by Django 3.2.5 on 2021-07-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0013_auto_20210727_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='hostel',
            field=models.CharField(choices=[('8', 'Barak')], max_length=256, verbose_name='Hostel'),
        ),
    ]
