# Generated by Django 3.2.5 on 2021-07-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0014_alter_habmodel_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='hostel',
            field=models.CharField(choices=[(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.siteuser'), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.siteuser'))], max_length=256, verbose_name='Hostel'),
        ),
    ]
