# Generated by Django 3.2rc1 on 2021-07-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0014_alter_habmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habmodel',
            options={'ordering': ['hostel', '-status', 'date_of_arrival'], 'permissions': (('can_view_lohit_hostel_data', 'can view lohit hostel data'), ('can_view_brahma_hostel_data', 'can view brahma hostel data'), ('can_view_siang_hostel_data', 'can view siang hostel data'), ('can_view_manas_hostel_data', 'can view manas hostel data'), ('can_view_disang_hostel_data', 'can view disang hostel data'), ('can_view_kameng_hostel_data', 'can view kameng hostel data'), ('can_view_umiam_hostel_data', 'can view umiam hostel data'), ('can_view_barak_hostel_data', 'can view barak hostel data'), ('can_view_kapili_hostel_data', 'can view kapili hostel data'), ('can_view_dihing_hostel_data', 'can view dihing hostel data'), ('can_view_suban_hostel_data', 'can view subansiri hostel data'), ('can_view_dhan_hostel_data', 'can view dhansiri hostel data'), ('can_view_msh_hostel_data', 'can view msh hostel data'))},
        ),
    ]
