# Generated by Django 3.2.5 on 2021-08-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0014_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
