# Generated by Django 3.2.5 on 2021-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0014_alter_habmodel_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='habmodel',
            name='invite_sent',
            field=models.CharField(choices=[('Invited', 'Invited'), ('Not Invited', 'Not Invited')], default='Not Invited', max_length=256, null=True),
        ),
    ]
