# Generated by Django 3.2.5 on 2021-08-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0015_delete_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='fee_to_be_paid',
            field=models.IntegerField(default=0, verbose_name='Fee to be Paid'),
        ),
    ]
