# Generated by Django 3.2.5 on 2021-09-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0015_habmodel_invite_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='programme',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.Des', 'B.Des'), ('M.Tech', 'M.Tech'), ('M.Des', 'M.Des'), ('M.A.', 'M.A.'), ('M.Sc.', 'M.Sc.'), ('MSR', 'MSR'), ('PHD/IPDF', 'PHD/IPDF'), ('Project Staff', 'Project Staff')], max_length=256, verbose_name='Programme'),
        ),
    ]
