# Generated by Django 3.2.5 on 2021-09-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0016_alter_habmodel_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='roll_number',
            field=models.CharField(help_text='Enter a valid 9 digit Roll Number.', max_length=9, verbose_name='Roll No.'),
        ),
    ]
