# Generated by Django 3.2.5 on 2021-07-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0016_alter_habmodel_hostel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habmodel',
            options={'ordering': ['hostel', '-status', '-time_of_submission']},
        ),
    ]
