# Generated by Django 3.2.5 on 2021-07-27 16:59

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_siteuser_data'),
        ('hab_portal', '0017_alter_habmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='user',
            field=models.ForeignKey(choices=[(users.models.SiteUser, users.models.SiteUser)], on_delete=django.db.models.deletion.CASCADE, to='users.siteuser'),
        ),
    ]
