# Generated by Django 3.2.5 on 2021-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0017_auto_20210830_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='roll_number',
            field=models.IntegerField(verbose_name='Roll No.'),
        ),
    ]
