# Generated by Django 3.2.5 on 2021-08-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0018_alter_habmodel_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='email',
            field=models.EmailField(max_length=500, verbose_name='Email'),
        ),
    ]
