# Generated by Django 3.2.5 on 2021-10-02 12:00

from django.db import migrations, models
import hab_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0018_auto_20210914_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='returning_from_state',
            field=models.CharField(choices=[('Other (Foreign Country)', 'Other (Foreign Country)'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry')], max_length=256, null=True, verbose_name='Returning from (state)'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='roll_number',
            field=models.CharField(help_text='Enter a valid 9 digit Roll Number.', max_length=100, validators=[hab_portal.models.validate_digit_length], verbose_name='Roll No.'),
        ),
    ]
