# Generated by Django 3.2.5 on 2021-07-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_siteuser_data'),
        ('hab_portal', '0018_alter_habmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.siteuser'),
        ),
    ]
