# Generated by Django 3.2.5 on 2021-07-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0015_alter_habmodel_options'),
        ('hab_portal', '0019_alter_habmodel_user'),
    ]

    operations = [
    ]
