# Generated by Django 3.2.5 on 2021-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0020_merge_20210728_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='status',
            field=models.CharField(choices=[(1, 'Approved'), (0, 'Pending'), (-1, 'Rejected')], default=0, max_length=256),
        ),
    ]
