# Generated by Django 3.2.5 on 2021-07-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0023_alter_habmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Roll No.'),
        ),
    ]
