# Generated by Django 3.2.5 on 2021-07-29 14:18

from django.db import migrations, models
import hab_portal.models
import hab_portal.storage


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0024_alter_habmodel_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='date_of_arrival',
            field=models.DateField(null=True, verbose_name='Date of Arrival'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='fee_paid',
            field=models.IntegerField(null=True, verbose_name='Fee Paid'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='fee_receipt',
            field=models.FileField(help_text='Upload a .PDF file not greater than 10 MB in size.', null=True, storage=hab_portal.storage.OverwriteStorage(), upload_to=hab_portal.models.upload_file_name, validators=[hab_portal.models.validate_file_size, hab_portal.models.validate_file_extension], verbose_name='Fee Receipt'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='locked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='roll_number',
            field=models.IntegerField(null=True, verbose_name='Roll No.'),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habmodel',
            name='status',
            field=models.CharField(choices=[('0', 'Approved'), ('1', 'Pending'), ('-1', 'Rejected')], default='1', max_length=256, null=True),
        ),
    ]
