# Generated by Django 3.2.5 on 2021-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0030_alter_habmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=256, null=True),
        ),
    ]
