# Generated by Django 3.2.5 on 2021-08-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0032_remove_habmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habmodel',
            name='hostel',
            field=models.CharField(choices=[('lohit', 'Lohit'), ('brahmaputra', 'Brahmaputra'), ('siang', 'Siang'), ('manas', 'Manas'), ('disang', 'Disang'), ('kameng', 'Kameng'), ('umiam', 'Umiam'), ('barak', 'Barak'), ('kapili', 'Kapili'), ('dihing', 'Dihing'), ('subansiri', 'Subansiri'), ('dhansiri', 'Dhansiri'), ('msh', 'Married Scholar Hostel')], max_length=256, null=True, verbose_name='Hostel'),
        ),
    ]
