# Generated by Django 3.2.5 on 2021-08-31 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_portal', '0019_alter_habmodel_email'),
        ('hab_portal', '0033_alter_habmodel_hostel'),
    ]

    operations = [
    ]
