
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-15T09:31:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "47b10718dc0a8bd0c521c9dc1a51d986a5f36a59",
 "version": "2.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
