# Generated by Django 3.2.5 on 2021-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='textfield',
            field=models.TextField(blank=True),
        ),
    ]
