# Generated by Django 3.2.5 on 2021-07-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_siteuser_data'),
        ('forms', '0002_alter_sampleform_textfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleForm',
            new_name='SampleModel',
        ),
    ]
