# Generated by Django 3.2.5 on 2021-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_mshmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mshmodel',
            name='phone_number_permanent',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='mshmodel',
            name='phone_number_present',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
