# Generated by Django 3.2.5 on 2021-07-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210715_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='mshmodel',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
