# Generated by Django 3.2.5 on 2021-07-16 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_mshmodel_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mshmodel',
            name='time_of_submission',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
