# Generated by Django 3.2.5 on 2021-07-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_mshmodel_time_of_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mshmodel',
            name='status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
