# Generated by Django 3.2.5 on 2021-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_mshmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mshmodel',
            name='dependents',
            field=models.TextField(blank=True, verbose_name='Dependents'),
        ),
    ]
